// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTmGBRqBFoduAIIyeTMMvJBTRQNaGPc68',
    appId: '1:454503718694:web:95c6d4a54191cada3f2be7',
    messagingSenderId: '454503718694',
    projectId: 'study-sync-3e158',
    authDomain: 'study-sync-3e158.firebaseapp.com',
    storageBucket: 'study-sync-3e158.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnoymvB_IZK2AlbWDmkZoi_za7h28JU4Y',
    appId: '1:454503718694:android:8ba53916c52378533f2be7',
    messagingSenderId: '454503718694',
    projectId: 'study-sync-3e158',
    storageBucket: 'study-sync-3e158.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUnK0s5mED2gb5V5mYgfKBKJlb7qv2toY',
    appId: '1:454503718694:ios:11f042ad3ba62b953f2be7',
    messagingSenderId: '454503718694',
    projectId: 'study-sync-3e158',
    storageBucket: 'study-sync-3e158.firebasestorage.app',
    iosBundleId: 'com.example.studySync',
  );
}
